# Generated by Django 4.2.17 on 2024-12-08 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alwayaApply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.AlterField(
            model_name='application',
            name='freelancer',
            field=models.ForeignKey(limit_choices_to={'role': 'freelancer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
