# Generated by Django 4.2.16 on 2024-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwayaApply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='due_to',
            field=models.DateField(auto_now_add=True),
        ),
    ]
