# Generated by Django 5.1.4 on 2024-12-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwayaApply', '0002_job_location_alter_job_level_alter_job_workingmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Egypt', max_length=200),
        ),
    ]
