# Generated by Django 5.1.4 on 2024-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwayaApply', '0003_application_company_alter_application_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Egypt', max_length=200),
        ),
    ]
