# Generated by Django 4.2.16 on 2024-12-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alwayaApply', '0003_alter_application_due_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED')], default='pending', max_length=200),
        ),
    ]
