# Generated by Django 5.1.3 on 2024-12-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_employer_id_alter_freelancer_id_alter_offer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jop',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='jop',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='jop',
            new_name='job',
        ),
    ]
