# Generated by Django 5.1.3 on 2024-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_rename_jop_job_rename_jop_application_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='connects',
            field=models.IntegerField(),
        ),
    ]
