# Generated by Django 4.2.16 on 2024-12-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='UserImages/'),
        ),
    ]
