# Generated by Django 4.2.16 on 2024-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
