# Generated by Django 5.1.4 on 2024-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('company', 'COMPANY'), ('freelancer', 'FREELANCER')], default='freelancer', max_length=200),
        ),
    ]
